### ISSUE TITLE
Doesn't work in Chrome or Opera

### ISSUE THREAD

**Issue by thSoft** [googlecreativelab/aiexperiments-drum-machine#1]
https://aiexperiments.withgoogle.com/drum-machine/view/ doesn't work in these browsers:
* Chrome 54.0.2840.98 
* Opera 41.0

The error message is: `Oops, sorry for the tech trouble. For the best experience, view in Chrome browser.`, which is especially funny in Chrome. :D

It works in:
* Firefox 49.0.2
* Safari 9.1.3

**Comment by dtnewman** [comment]
I'm using Chrome 54.0.2840.98 on a Macbook Pro (OS X El Capitan 10.11.6) and it works just fine. Maybe you have a plugin that is causing an issue? What OS are you using?

**Comment by thSoft** [comment]
- My OS is exactly the same.
- I get the same error with all plugins disabled.
- I attach the console output in Chrome.

[aiexperiments.withgoogle.com-1479395781698.txt](https://github.com/googlecreativelab/aiexperiments-drum-machine/files/597716/aiexperiments.withgoogle.com-1479395781698.txt)

**Comment by dtnewman** [comment]
I am getting the lines `THREE.WebGLRenderer 75` and `Uncaught ReferenceError: ytcfg is not defined(…)` as well. But I'm not getting `Error creating WebGL context.`. Also not getting the `ERR_BLOCKED_BY_CLIENT` errors.

Looking at https://www.keycdn.com/support/how-to-solve-err-blocked-by-client/ and http://stackoverflow.com/questions/23341765/getting-neterr-blocked-by-client-error-on-some-ajax-calls, it seems that the `ERR_BLOCKED_BY_CLIENT` errors are usually caused by ad blockers and other extensions. Do you have an ad-blocker installed?

**Comment by mannytan** [comment]
The error message is created if the browser can't find a webGL context. Are
you able to view other WebGL projects okay?

**Comment by mannytan** [comment]
Uncaught ReferenceError: ytcfg is not defined looks to be a YouTube iFrames
issue
http://stackoverflow.com/questions/40622204/uncaught-referenceerror-ytcfg-is-not-defined
(StackOverflow).
A simple and inelegant workaround would be to refresh your browser.

**Comment by thSoft** [comment]
Other WebGL projects don't work either, so the problem is with my browser definitely. E.g.  http://helloracer.com/webgl/ also outputs:

```
Three.js:242 Error creating WebGL context.(anonymous function) @ Three.js:242
Three.js:242 Uncaught TypeError: Cannot read property 'clearColor' of null(…)
```
